import os
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models

# This script is meant to be run offline to train the CNN false-positive classifier.
# It expects a directory of 32x32 grayscale numpy arrays or images generated by the simulator.
# Data format assumed: X_train.npy (N, 32, 32, 1) and y_train.npy (N,) where 1=real target, 0=false positive (glint/noise)

def build_model():
    model = models.Sequential([
        layers.Input(shape=(32, 32, 1)),
        # MobileNet-style depthwise separable convolutions for speed
        layers.SeparableConv2D(16, (3, 3), activation='relu', padding='same'),
        layers.MaxPooling2D((2, 2)),
        layers.SeparableConv2D(32, (3, 3), activation='relu', padding='same'),
        layers.MaxPooling2D((2, 2)),
        layers.SeparableConv2D(64, (3, 3), activation='relu', padding='same'),
        layers.GlobalAveragePooling2D(),
        layers.Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return model

def train_and_export():
    print("Loading simulated dataset...")
    # Mock data generation for illustration:
    # In reality, the JS simulator would dump labeled crops during a headless run.
    N = 5000
    X_train = np.random.rand(N, 32, 32, 1).astype(np.float32)
    y_train = np.random.randint(0, 2, size=(N,))
    
    model = build_model()
    model.summary()
    
    print("Training CNN...")
    model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)
    
    export_dir = 'tfjs_model'
    print(f"Exporting model to {export_dir}...")
    
    # Save keras model
    model.save('cnn_classifier.h5')
    
    # Convert to TFJS format
    # Requires: pip install tensorflowjs
    os.system('tensorflowjs_converter --input_format keras cnn_classifier.h5 tfjs_model')
    print("Export complete. Move 'tfjs_model' to the Vite public folder.")

if __name__ == '__main__':
    train_and_export()
