import * as tf from '@tensorflow/tfjs';

let model = null;
let modelLoading = false;

// Initialize and load the model
export async function loadCNNClassifier() {
  if (model || modelLoading) return;
  modelLoading = true;
  try {
    // Expects the model to be generated by python script and placed in public/model/
    model = await tf.loadLayersModel('/model/model.json');
    console.log("CNN Classifier loaded successfully.");
  } catch (err) {
    console.warn("CNN model not found at /model/model.json. Falling back to mock classifier.");
    model = 'MOCK'; // Use a mock if model file is missing during development
  }
}

// Extract a 32x32 crop around a candidate and run inference
export async function classifyCandidates(candidates, gl, width, height, pixelRatio = 1) {
  if (!model) return candidates; // pass through if not loaded
  
  // Read full pixels once to extract crops (inefficient but necessary for WebGL without readRenderTarget)
  const buffer = new Uint8Array(width * height * 4);
  try {
    gl.readPixels(0, 0, width, height, gl.RGBA, gl.UNSIGNED_BYTE, buffer);
  } catch(e) {
    return candidates;
  }
  
  const validated = [];
  
  for (let cand of candidates) {
    const cx = Math.floor(cand.box.x * pixelRatio); // box is in logical coords, scale to physical
    const cy = Math.floor(cand.box.y * pixelRatio); // box is in logical coords, scale to physical
    // remember: y in buffer might be flipped depending on how we read, but let's assume standard WebGL
    // actually, detector flipped Y for logical coords: y = height - y.
    // So to read from buffer, physical py = height - physical cy
    const cyBuffer = height - cy; 
    
    // We want a 32x32 crop around (cx, cy)
    const cropSize = 32;
    const half = cropSize / 2;
    const cropData = new Float32Array(cropSize * cropSize);
    
    for (let y = 0; y < cropSize; y++) {
      for (let x = 0; x < cropSize; x++) {
        const px = Math.min(Math.max(cx - half + x, 0), width - 1);
        const py = Math.min(Math.max(cyBuffer - half + y, 0), height - 1);
        
        const idx = (py * width + px) * 4;
        // Grayscale conversion
        const val = (buffer[idx] + buffer[idx+1] + buffer[idx+2]) / 3.0;
        cropData[y * cropSize + x] = val / 255.0; // normalize
      }
    }
    
    let prob = 0.5;
    if (model === 'MOCK') {
      // Mock ML logic: If it's the exact center offset where we spawn the sun glint decoy (x+15, y-10)
      // we reject it. But here we just use the variance to fake ML logic.
      if (cand.variance > 800) prob = 0.1; // Probably noise/glint
      else prob = 0.9;
    } else {
      const tensor = tf.tensor4d(cropData, [1, 32, 32, 1]);
      const prediction = model.predict(tensor);
      const data = await prediction.data();
      prob = data[0];
      tensor.dispose();
      prediction.dispose();
    }
    
    // threshold
    if (prob > 0.5) {
      // It's a real target, keep it
      // Boost confidence slightly because CNN validated it
      cand.confidence = Math.min(1.0, cand.confidence * 1.2);
      validated.push(cand);
    }
  }
  
  return validated;
}
